export const GET_EDITOR_MODEL_FAILURE = "GET_EDITOR_MODEL_FAILURE";
export const GET_EDITOR_MODEL_REQUEST = "GET_EDITOR_MODEL_REQUEST";
export const GET_EDITOR_MODEL_SUCCESS = "GET_EDITOR_MODEL_SUCCESS";

export const GET_PLAYER_MODEL_FAILURE = "GET_PLAYER_MODEL_FAILURE";
export const GET_PLAYER_MODEL_REQUEST = "GET_PLAYER_MODEL_REQUEST";
export const GET_PLAYER_MODEL_SUCCESS = "GET_PLAYER_MODEL_SUCCESS";

export const GET_DOCUMENTS_FAILURE = "GET_DOCUMENTS_FAILURE";
export const GET_DOCUMENTS_REQUEST = "GET_DOCUMENTS_REQUEST";
export const GET_DOCUMENTS_SUCCESS = "GET_DOCUMENTS_SUCCESS";
